server {
    listen 80;
    server_name api.silkriti.in;

    client_max_body_size 15M;

    location / {
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        'upgrade';
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
    }

    # Serve uploaded files directly from disk — bypasses Node.js
    location /uploads/ {
        alias   /home/ubuntu/silkriti-backend/uploads/;
        expires 60d;
        add_header Cache-Control "public";
    }
}
